export const notification = {};

export const requestType = {
  POST: 'post',
  GET: 'get',
  PUT: 'put',
  DELETE: 'delete',
};

export const endPoints = {
  sendCode: 'sendCode',
  registerMerchant: 'registerMerchant',
  loginMerchant: 'loginMerchant',
  resetPasswordMerchant: 'resetPasswordMerchant',
  addProduct: 'addProduct',
  getProduct: 'getProduct',
  updateProduct: 'updateProduct',
  deleteProduct: 'deleteProduct',
  getAllAllergies: 'getAllAllergies',
  getOrderByMerchant: 'getOrderByMerchant',
  updateOrderStatus: 'updateOrderStatus',
  getMerchantProfile: 'getMerchantProfile',
  updateMerchantProfile: 'updateMerchantProfile',
  changePasswordMerchant: 'changePasswordMerchant',
  getCertificationLink: 'getCertificationLink',
  getAllergiesCategories: 'getAllergiesCategories',
  getAllergiesByCategory: 'getAllergiesByCategory',
  merchantDashboard: 'merchantDashboard',
  createFoodCategory: 'createFoodCategory',
  getFoodCategoriesById: 'getFoodCategoriesById',
  updateFoodCategory: 'updateFoodCategory',
  deleteFoodCategory: 'deleteFoodCategory',
  getPrivateOrderByMerchant: 'getPrivateOrderByMerchant',
  updatePrivateOrderStatus: 'updatePrivateOrderStatus',
  getAllFAQs: 'getAllFAQs',
  getMerchantPaymentHistory: 'getMerchantPaymentHistory',
  addMerchantAccountDetails: 'addMerchantAccountDetails',
  getMerchantAccountDetails: 'getMerchantAccountDetails',
  updateMerchantAccountDetails: 'updateMerchantAccountDetails',
  createSupportMessage: 'createSupportMessage',
  getSupportMessagesById: 'getSupportMessagesById',
  connectAccount: 'connectAccountMerchant',
  sendResetCodeMerchant: 'sendResetCodeMerchant',
  getAllFoodCategories:"getAllFoodCategories",
  getAllPortionSections:"getAllPortionSections",
};
